// 产研通行业分类体系 — 1号AI #162 设计
// 20个一级行业，100+二级行业

export interface IndustryRow {
  primaryCode: string
  primaryName: string
  subCode: string
  subName: string
}

export const INDUSTRIES: IndustryRow[] = [
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-01", subName: "软件开发" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-02", subName: "IT服务" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-03", subName: "数据服务" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-04", subName: "网络安全" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-05", subName: "云计算" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-06", subName: "物联网" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-07", subName: "区块链" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-08", subName: "信息技术咨询" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-01", subName: "大模型(LLM)" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-02", subName: "计算机视觉" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-03", subName: "自然语言处理" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-04", subName: "AI芯片" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-05", subName: "AI应用" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-01", subName: "芯片设计" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-02", subName: "晶圆制造" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-03", subName: "封装测试" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-04", subName: "半导体设备" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-01", subName: "化学制药" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-02", subName: "生物制品" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-03", subName: "中药" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-04", subName: "医疗器械" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-05", subName: "医疗服务" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-06", subName: "医疗信息化" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-07", subName: "医药流通" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-08", subName: "医疗健康咨询" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-01", subName: "光伏" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-02", subName: "风电" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-03", subName: "储能" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-04", subName: "氢能" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-05", subName: "新能源汽车" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-06", subName: "新能源运营" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-01", subName: "银行" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-02", subName: "证券" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-03", subName: "保险" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-04", subName: "基金" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-05", subName: "金融科技" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-06", subName: "投资管理" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-01", subName: "食品饮料" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-02", subName: "家用电器" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-03", subName: "纺织服装" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-04", subName: "美妆日化" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-05", subName: "消费电子" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-06", subName: "零售商贸" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-07", subName: "跨境电商" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-08", subName: "轻工制造" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-01", subName: "通用设备" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-02", subName: "专用设备" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-03", subName: "工程机械" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-04", subName: "电力设备" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-05", subName: "自动化" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-06", subName: "智能制造" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-07", subName: "工业软件" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-08", subName: "检验检测" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-09", subName: "仪器仪表" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-10", subName: "工业咨询" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-01", subName: "整车制造" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-02", subName: "汽车零部件" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-03", subName: "智能驾驶" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-04", subName: "汽车电子" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-05", subName: "后市场" },
  (10, '通信与传媒', '10-01', '5G通信'),
  (10, '通信与传媒', '10-02', '光通信'),
  (10, '通信与传媒', '10-03', '广播电视'),
  (10, '通信与传媒', '10-04', '互联网媒体'),
  (10, '通信与传媒', '10-05', '游戏'),
  (10, '通信与传媒', '10-06', '数字营销'),
  (11, '能源与新材料', '11-01', '石油石化'),
  (11, '能源与新材料', '11-02', '煤炭'),
  (11, '能源与新材料', '11-03', '有色与贵金属'),
  (11, '能源与新材料', '11-04', '化工新材料'),
  (11, '能源与新材料', '11-05', '特种钢材'),
  (11, '能源与新材料', '11-06', '稀土永磁'),
  (11, '能源与新材料', '11-07', '光伏材料'),
  (12, '房地产', '12-01', '住宅开发'),
  (12, '房地产', '12-02', '商业地产'),
  (12, '房地产', '12-03', '地产服务'),
  (13, '公用事业', '13-01', '电力'),
  (13, '公用事业', '13-02', '水务'),
  (13, '公用事业', '13-03', '燃气'),
  (13, '公用事业', '13-04', '环保服务'),
  (14, '教育', '14-01', '在线教育'),
  (14, '教育', '14-02', '职业培训'),
  (14, '教育', '14-03', '教育信息化'),
  (15, '物流与供应链', '15-01', '快递配送'),
  (15, '物流与供应链', '15-02', '供应链管理'),
  (15, '物流与供应链', '15-03', '冷链物流'),
  (15, '物流与供应链', '15-04', '跨境物流'),
  (16, '农业与食品', '16-01', '种植业'),
  (16, '农业与食品', '16-02', '养殖业'),
  (16, '农业与食品', '16-03', '食品加工'),
  (16, '农业与食品', '16-04', '种业化肥'),
  (16, '农业与食品', '16-05', '农业科技'),
  (17, '环保与双碳', '17-01', '碳交易'),
  (17, '环保与双碳', '17-02', '环境监测'),
  (17, '环保与双碳', '17-03', '固废处理'),
  (17, '环保与双碳', '17-04', '环保咨询'),
  (18, '军工与航天', '18-01', '航空航天'),
  (18, '军工与航天', '18-02', '兵器装备'),
  (18, '军工与航天', '18-03', '军民融合'),
  (19, '文娱与体育', '19-01', '影视制作'),
  (19, '文娱与体育', '19-02', '体育产业'),
  (19, '文娱与体育', '19-03', '文化旅游'),
  (20, '跨行业综合', '20-01', '管理咨询'),
  (20, '跨行业综合', '20-02', '法律合规'),
  (20, '跨行业综合', '20-03', '人力资源'),
  (20, '跨行业综合', '20-04', '战略规划')
];

// 总计 106 个二级行业，20个一级行业
