// 产研通行业分类体系 — 1号AI #162 设计
// 20个一级行业，100+二级行业

export interface IndustryRow {
  primaryCode: string
  primaryName: string
  subCode: string
  subName: string
}

export const INDUSTRIES: IndustryRow[] = [
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-01", subName: "软件开发" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-02", subName: "IT服务" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-03", subName: "数据服务" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-04", subName: "网络安全" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-05", subName: "云计算" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-06", subName: "物联网" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-07", subName: "区块链" },
  { primaryCode: "01", primaryName: "信息技术", subCode: "01-08", subName: "信息技术咨询" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-01", subName: "大模型(LLM)" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-02", subName: "计算机视觉" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-03", subName: "自然语言处理" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-04", subName: "AI芯片" },
  { primaryCode: "02", primaryName: "人工智能", subCode: "02-05", subName: "AI应用" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-01", subName: "芯片设计" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-02", subName: "晶圆制造" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-03", subName: "封装测试" },
  { primaryCode: "03", primaryName: "半导体", subCode: "03-04", subName: "半导体设备" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-01", subName: "化学制药" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-02", subName: "生物制品" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-03", subName: "中药" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-04", subName: "医疗器械" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-05", subName: "医疗服务" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-06", subName: "医疗信息化" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-07", subName: "医药流通" },
  { primaryCode: "04", primaryName: "医疗健康", subCode: "04-08", subName: "医疗健康咨询" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-01", subName: "光伏" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-02", subName: "风电" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-03", subName: "储能" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-04", subName: "氢能" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-05", subName: "新能源汽车" },
  { primaryCode: "05", primaryName: "新能源", subCode: "05-06", subName: "新能源运营" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-01", subName: "银行" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-02", subName: "证券" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-03", subName: "保险" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-04", subName: "基金" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-05", subName: "金融科技" },
  { primaryCode: "06", primaryName: "金融", subCode: "06-06", subName: "投资管理" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-01", subName: "食品饮料" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-02", subName: "家用电器" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-03", subName: "纺织服装" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-04", subName: "美妆日化" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-05", subName: "消费电子" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-06", subName: "零售商贸" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-07", subName: "跨境电商" },
  { primaryCode: "07", primaryName: "消费品", subCode: "07-08", subName: "轻工制造" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-01", subName: "通用设备" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-02", subName: "专用设备" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-03", subName: "工程机械" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-04", subName: "电力设备" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-05", subName: "自动化" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-06", subName: "智能制造" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-07", subName: "工业软件" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-08", subName: "检验检测" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-09", subName: "仪器仪表" },
  { primaryCode: "08", primaryName: "工业", subCode: "08-10", subName: "工业咨询" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-01", subName: "整车制造" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-02", subName: "汽车零部件" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-03", subName: "智能驾驶" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-04", subName: "汽车电子" },
  { primaryCode: "09", primaryName: "汽车", subCode: "09-05", subName: "后市场" },
  { primaryCode: "10", primaryName: "通信与传媒", subCode: "10-01", subName: "5G通信" },
  { primaryCode: "10", primaryName: "通信与传媒", subCode: "10-02", subName: "光通信" },
  { primaryCode: "10", primaryName: "通信与传媒", subCode: "10-03", subName: "广播电视" },
  { primaryCode: "10", primaryName: "通信与传媒", subCode: "10-04", subName: "互联网媒体" },
  { primaryCode: "10", primaryName: "通信与传媒", subCode: "10-05", subName: "游戏" },
  { primaryCode: "10", primaryName: "通信与传媒", subCode: "10-06", subName: "数字营销" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-01", subName: "石油石化" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-02", subName: "煤炭" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-03", subName: "有色与贵金属" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-04", subName: "化工新材料" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-05", subName: "特种钢材" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-06", subName: "稀土永磁" },
  { primaryCode: "11", primaryName: "能源与新材料", subCode: "11-07", subName: "光伏材料" },
  { primaryCode: "12", primaryName: "房地产", subCode: "12-01", subName: "住宅开发" },
  { primaryCode: "12", primaryName: "房地产", subCode: "12-02", subName: "商业地产" },
  { primaryCode: "12", primaryName: "房地产", subCode: "12-03", subName: "地产服务" },
  { primaryCode: "13", primaryName: "公用事业", subCode: "13-01", subName: "电力" },
  { primaryCode: "13", primaryName: "公用事业", subCode: "13-02", subName: "水务" },
  { primaryCode: "13", primaryName: "公用事业", subCode: "13-03", subName: "燃气" },
  { primaryCode: "13", primaryName: "公用事业", subCode: "13-04", subName: "环保服务" },
  { primaryCode: "14", primaryName: "教育", subCode: "14-01", subName: "在线教育" },
  { primaryCode: "14", primaryName: "教育", subCode: "14-02", subName: "职业培训" },
  { primaryCode: "14", primaryName: "教育", subCode: "14-03", subName: "教育信息化" },
  { primaryCode: "15", primaryName: "物流与供应链", subCode: "15-01", subName: "快递配送" },
  { primaryCode: "15", primaryName: "物流与供应链", subCode: "15-02", subName: "供应链管理" },
  { primaryCode: "15", primaryName: "物流与供应链", subCode: "15-03", subName: "冷链物流" },
  { primaryCode: "15", primaryName: "物流与供应链", subCode: "15-04", subName: "跨境物流" },
  { primaryCode: "16", primaryName: "农业与食品", subCode: "16-01", subName: "种植业" },
  { primaryCode: "16", primaryName: "农业与食品", subCode: "16-02", subName: "养殖业" },
  { primaryCode: "16", primaryName: "农业与食品", subCode: "16-03", subName: "食品加工" },
  { primaryCode: "16", primaryName: "农业与食品", subCode: "16-04", subName: "种业化肥" },
  { primaryCode: "16", primaryName: "农业与食品", subCode: "16-05", subName: "农业科技" },
  { primaryCode: "17", primaryName: "环保与双碳", subCode: "17-01", subName: "碳交易" },
  { primaryCode: "17", primaryName: "环保与双碳", subCode: "17-02", subName: "环境监测" },
  { primaryCode: "17", primaryName: "环保与双碳", subCode: "17-03", subName: "固废处理" },
  { primaryCode: "17", primaryName: "环保与双碳", subCode: "17-04", subName: "环保咨询" },
  { primaryCode: "18", primaryName: "军工与航天", subCode: "18-01", subName: "航空航天" },
  { primaryCode: "18", primaryName: "军工与航天", subCode: "18-02", subName: "兵器装备" },
  { primaryCode: "18", primaryName: "军工与航天", subCode: "18-03", subName: "军民融合" },
  { primaryCode: "19", primaryName: "文娱与体育", subCode: "19-01", subName: "影视制作" },
  { primaryCode: "19", primaryName: "文娱与体育", subCode: "19-02", subName: "体育产业" },
  { primaryCode: "19", primaryName: "文娱与体育", subCode: "19-03", subName: "文化旅游" },
  { primaryCode: "20", primaryName: "跨行业综合", subCode: "20-01", subName: "管理咨询" },
  { primaryCode: "20", primaryName: "跨行业综合", subCode: "20-02", subName: "法律合规" },
  { primaryCode: "20", primaryName: "跨行业综合", subCode: "20-03", subName: "人力资源" },
  { primaryCode: "20", primaryName: "跨行业综合", subCode: "20-04", subName: "战略规划" }
];

// 总计 106 个二级行业，20个一级行业
